import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import MainMenuItem from '../components/MainMenuItem';

const App = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="max-w-5xl mx-auto flex flex-col items-center">
      <div className="w-full flex items-center pt-4 pb-12">
        <div className="flex-1 flex justify-center">
          <MainMenuItem href="/">Home</MainMenuItem>
          <MainMenuItem href="/blog">Blog</MainMenuItem>
          <MainMenuItem href="/contact">Contact</MainMenuItem>
        </div>
      </div>
      <Component {...pageProps} />
    </div>
  </>
);

export default App;
